package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/pluszero/dental-video-api/internal/gqlconv"
	"github.com/pluszero/dental-video-api/internal/graph/generated"
	"github.com/pluszero/dental-video-api/internal/models"
)

// UpdateOrganization is the resolver for the updateOrganization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, input generated.UpdateOrganizationInput) (*generated.Organization, error) {
	o, err := r.svc.UpdateOrganization(ctx, gqlconv.PatchFromInput(input))
	if err != nil {
		return nil, err
	}
	return gqlconv.ToOrganization(o), nil
}

// GenerateAnalyticsInsight is the resolver for the generateAnalyticsInsight field.
func (r *mutationResolver) GenerateAnalyticsInsight(ctx context.Context, periodDays *int) (*generated.AnalyticsInsight, error) {
	days := 30
	if periodDays != nil {
		days = *periodDays
	}
	ins, err := r.svc.GenerateAnalyticsInsight(ctx, days)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToAnalyticsInsight(ins), nil
}

// UpdateWatchProgress is the resolver for the updateWatchProgress field.
func (r *mutationResolver) UpdateWatchProgress(ctx context.Context, input generated.UpdateWatchProgressInput) (*generated.WatchProgress, error) {
	completed := false
	if input.Completed != nil {
		completed = *input.Completed
	}
	wp := models.WatchProgress{
		VideoID: input.VideoID, LearnerID: input.LearnerID,
		PositionSec: input.PositionSec, Completed: completed,
	}
	updated, err := r.svc.UpdateProgressWithEvents(ctx, wp)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToProgress(updated), nil
}

// CreateVideoNote is the resolver for the createVideoNote field.
func (r *mutationResolver) CreateVideoNote(ctx context.Context, input generated.CreateVideoNoteInput) (*generated.VideoNote, error) {
	n := models.VideoNote{
		VideoID: input.VideoID, LearnerID: input.LearnerID,
		TimestampSec: input.TimestampSec, Body: input.Body,
	}
	created, err := r.svc.CreateNote(ctx, n)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToNote(created), nil
}

// DeleteVideoNote is the resolver for the deleteVideoNote field.
func (r *mutationResolver) DeleteVideoNote(ctx context.Context, id string) (bool, error) {
	return r.svc.DeleteNote(ctx, id)
}

// ToggleBookmark is the resolver for the toggleBookmark field.
func (r *mutationResolver) ToggleBookmark(ctx context.Context, videoID string, learnerID string) (*generated.Bookmark, error) {
	bm, err := r.svc.ToggleBookmark(ctx, videoID, learnerID)
	if err != nil || bm == nil {
		return nil, err
	}
	return gqlconv.ToBookmark(*bm), nil
}

// EnrollLearningPath is the resolver for the enrollLearningPath field.
func (r *mutationResolver) EnrollLearningPath(ctx context.Context, pathID string, learnerID string) (*generated.LearningPath, error) {
	if err := r.svc.EnrollPathWithEvents(ctx, pathID, learnerID); err != nil {
		return nil, err
	}
	path, ok, err := r.svc.GetPath(ctx, pathID)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToPath(path), nil
}

// SubmitQuizAttempt is the resolver for the submitQuizAttempt field.
func (r *mutationResolver) SubmitQuizAttempt(ctx context.Context, input generated.SubmitQuizAttemptInput) (*generated.QuizAttempt, error) {
	attempt, ok, err := r.svc.SubmitQuizAttempt(ctx, input.QuizID, input.LearnerID, input.Answers)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToAttempt(attempt), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*generated.Health, error) {
	return gqlconv.ToHealth(), nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*generated.DashboardStats, error) {
	d, err := r.svc.Dashboard(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToDashboard(d), nil
}

// CurrentSession is the resolver for the currentSession field.
func (r *queryResolver) CurrentSession(ctx context.Context) (*generated.Session, error) {
	sess, err := r.svc.CurrentSession(ctx)
	if err != nil || sess == nil {
		return nil, err
	}
	return gqlconv.ToSession(*sess), nil
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context) (*generated.Organization, error) {
	o, err := r.svc.GetOrganization(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToOrganization(o), nil
}

// UsageSummary is the resolver for the usageSummary field.
func (r *queryResolver) UsageSummary(ctx context.Context) (*generated.UsageSummary, error) {
	u, err := r.svc.UsageSummary(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToUsageSummary(u), nil
}

// TeamMembers is the resolver for the teamMembers field.
func (r *queryResolver) TeamMembers(ctx context.Context) ([]*generated.TeamMember, error) {
	members, users, err := r.svc.ListTeamMembers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.TeamMember, len(members))
	for i, m := range members {
		out[i] = gqlconv.ToTeamMember(m, users[i])
	}
	return out, nil
}

// AnalyticsBoard is the resolver for the analyticsBoard field.
func (r *queryResolver) AnalyticsBoard(ctx context.Context, periodDays *int) (*generated.AnalyticsBoard, error) {
	days := 30
	if periodDays != nil {
		days = *periodDays
	}
	b, err := r.svc.AnalyticsBoard(ctx, days)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToAnalyticsBoard(b), nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context, category *models.VideoCategory, skillLevel *models.SkillLevel, search *string, page *int, pageSize *int) (*generated.VideoPage, error) {
	p, ps := pageArgs(page, pageSize)
	s := ""
	if search != nil {
		s = *search
	}
	result, err := r.svc.PaginateVideos(ctx, gqlconv.EnumStr(category), gqlconv.LevelStr(skillLevel), s, p, ps)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToVideoPage(result), nil
}

// Video is the resolver for the video field.
func (r *queryResolver) Video(ctx context.Context, id string) (*generated.Video, error) {
	v, ok, err := r.svc.GetVideo(ctx, id)
	if err != nil || !ok {
		return nil, err
	}
	return gqlconv.ToVideo(v), nil
}

// FeaturedVideos is the resolver for the featuredVideos field.
func (r *queryResolver) FeaturedVideos(ctx context.Context) ([]*generated.Video, error) {
	videos, err := r.svc.FeaturedVideos(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToVideos(videos), nil
}

// Instructors is the resolver for the instructors field.
func (r *queryResolver) Instructors(ctx context.Context) ([]*generated.Instructor, error) {
	list, err := r.svc.ListInstructors(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Instructor, len(list))
	for i, inst := range list {
		out[i] = gqlconv.ToInstructor(inst)
	}
	return out, nil
}

// Instructor is the resolver for the instructor field.
func (r *queryResolver) Instructor(ctx context.Context, id string) (*generated.Instructor, error) {
	if l := loadersFrom(ctx); l != nil {
		thunk := l.InstructorByID.Load(ctx, id)
		return thunk()
	}
	i, ok, err := r.svc.GetInstructor(ctx, id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToInstructor(i), nil
}

// LearningPaths is the resolver for the learningPaths field.
func (r *queryResolver) LearningPaths(ctx context.Context, category *models.VideoCategory, skillLevel *models.SkillLevel) ([]*generated.LearningPath, error) {
	list, err := r.svc.ListPaths(ctx, gqlconv.EnumStr(category), gqlconv.LevelStr(skillLevel))
	if err != nil {
		return nil, err
	}
	return gqlconv.ToPaths(list), nil
}

// LearningPath is the resolver for the learningPath field.
func (r *queryResolver) LearningPath(ctx context.Context, id string) (*generated.LearningPath, error) {
	path, ok, err := r.svc.GetPath(ctx, id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToPath(path), nil
}

// MyProgress is the resolver for the myProgress field.
func (r *queryResolver) MyProgress(ctx context.Context, learnerID string) ([]*generated.WatchProgress, error) {
	list, err := r.svc.ListProgress(ctx, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.WatchProgress, len(list))
	for i, p := range list {
		out[i] = gqlconv.ToProgress(p)
	}
	return out, nil
}

// MyBookmarks is the resolver for the myBookmarks field.
func (r *queryResolver) MyBookmarks(ctx context.Context, learnerID string) ([]*generated.Bookmark, error) {
	list, err := r.svc.ListBookmarks(ctx, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Bookmark, len(list))
	for i, b := range list {
		out[i] = gqlconv.ToBookmark(b)
	}
	return out, nil
}

// VideoNotes is the resolver for the videoNotes field.
func (r *queryResolver) VideoNotes(ctx context.Context, videoID string, learnerID string) ([]*generated.VideoNote, error) {
	list, err := r.svc.ListNotes(ctx, videoID, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.VideoNote, len(list))
	for i, n := range list {
		out[i] = gqlconv.ToNote(n)
	}
	return out, nil
}

// Quizzes is the resolver for the quizzes field.
func (r *queryResolver) Quizzes(ctx context.Context, videoID *string) ([]*generated.Quiz, error) {
	vid := ""
	if videoID != nil {
		vid = *videoID
	}
	list, err := r.svc.ListQuizzes(ctx, vid)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Quiz, len(list))
	for i, q := range list {
		out[i] = gqlconv.ToQuiz(q)
	}
	return out, nil
}

// Quiz is the resolver for the quiz field.
func (r *queryResolver) Quiz(ctx context.Context, id string) (*generated.Quiz, error) {
	q, ok, err := r.svc.GetQuiz(ctx, id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToQuiz(q), nil
}

// MyQuizAttempts is the resolver for the myQuizAttempts field.
func (r *queryResolver) MyQuizAttempts(ctx context.Context, learnerID string) ([]*generated.QuizAttempt, error) {
	list, err := r.svc.ListAttempts(ctx, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.QuizAttempt, len(list))
	for i, a := range list {
		out[i] = gqlconv.ToAttempt(a)
	}
	return out, nil
}

// MyCertificates is the resolver for the myCertificates field.
func (r *queryResolver) MyCertificates(ctx context.Context, learnerID string) ([]*generated.Certificate, error) {
	list, err := r.svc.ListCertificates(ctx, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Certificate, len(list))
	for i, c := range list {
		out[i] = gqlconv.ToCertificate(c)
	}
	return out, nil
}

// DashboardUpdated is the resolver for the dashboardUpdated field.
func (r *subscriptionResolver) DashboardUpdated(ctx context.Context) (<-chan *generated.DashboardStats, error) {
	oid, err := r.svc.OrgID(ctx)
	if err != nil {
		return nil, err
	}
	ch := r.svc.Realtime.SubscribeDashboard(oid)
	go func() {
		<-ctx.Done()
		r.svc.Realtime.UnsubscribeDashboard(oid, ch)
	}()
	return ch, nil
}

// ProgressUpdated is the resolver for the progressUpdated field.
func (r *subscriptionResolver) ProgressUpdated(ctx context.Context, learnerID string) (<-chan *generated.WatchProgress, error) {
	ch := r.svc.Realtime.SubscribeProgress(learnerID)
	go func() {
		<-ctx.Done()
		r.svc.Realtime.UnsubscribeProgress(learnerID, ch)
	}()
	return ch, nil
}

// LearningActivity is the resolver for the learningActivity field.
func (r *subscriptionResolver) LearningActivity(ctx context.Context, learnerID string) (<-chan *generated.LearningActivityEvent, error) {
	ch := r.svc.Realtime.SubscribeActivity(learnerID)
	go func() {
		<-ctx.Done()
		r.svc.Realtime.UnsubscribeActivity(learnerID, ch)
	}()
	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
