package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"time"

	"github.com/pluszero/dental-video-api/internal/gqlconv"
	"github.com/pluszero/dental-video-api/internal/graph/generated"
	"github.com/pluszero/dental-video-api/internal/models"
)

// UpdateOrganization is the resolver for the updateOrganization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, input generated.UpdateOrganizationInput) (*generated.Organization, error) {
	o, err := r.svc.UpdateOrganization(ctx, gqlconv.PatchFromInput(input))
	if err != nil {
		return nil, err
	}
	mods, err := r.svc.ListSaasModules(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToOrganizationWithModules(o, mods), nil
}

// GenerateAnalyticsInsight is the resolver for the generateAnalyticsInsight field.
func (r *mutationResolver) GenerateAnalyticsInsight(ctx context.Context, periodDays *int) (*generated.AnalyticsInsight, error) {
	days := 30
	if periodDays != nil {
		days = *periodDays
	}
	ins, err := r.svc.GenerateAnalyticsInsight(ctx, days)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToAnalyticsInsight(ins), nil
}

// UpdateWatchProgress is the resolver for the updateWatchProgress field.
func (r *mutationResolver) UpdateWatchProgress(ctx context.Context, input generated.UpdateWatchProgressInput) (*generated.WatchProgress, error) {
	completed := false
	if input.Completed != nil {
		completed = *input.Completed
	}
	wp := models.WatchProgress{
		VideoID: input.VideoID, LearnerID: input.LearnerID,
		PositionSec: input.PositionSec, Completed: completed,
	}
	updated, err := r.svc.UpdateProgressWithEvents(ctx, wp)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToProgress(updated), nil
}

// CreateVideoNote is the resolver for the createVideoNote field.
func (r *mutationResolver) CreateVideoNote(ctx context.Context, input generated.CreateVideoNoteInput) (*generated.VideoNote, error) {
	n := models.VideoNote{
		VideoID: input.VideoID, LearnerID: input.LearnerID,
		TimestampSec: input.TimestampSec, Body: input.Body,
	}
	created, err := r.svc.CreateNote(ctx, n)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToNote(created), nil
}

// DeleteVideoNote is the resolver for the deleteVideoNote field.
func (r *mutationResolver) DeleteVideoNote(ctx context.Context, id string) (bool, error) {
	return r.svc.DeleteNote(ctx, id)
}

// ToggleBookmark is the resolver for the toggleBookmark field.
func (r *mutationResolver) ToggleBookmark(ctx context.Context, videoID string, learnerID string) (*generated.Bookmark, error) {
	bm, err := r.svc.ToggleBookmark(ctx, videoID, learnerID)
	if err != nil || bm == nil {
		return nil, err
	}
	return gqlconv.ToBookmark(*bm), nil
}

// EnrollLearningPath is the resolver for the enrollLearningPath field.
func (r *mutationResolver) EnrollLearningPath(ctx context.Context, pathID string, learnerID string) (*generated.LearningPath, error) {
	if err := r.svc.EnrollPathWithEvents(ctx, pathID, learnerID); err != nil {
		return nil, err
	}
	path, ok, err := r.svc.GetPath(ctx, pathID)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToPath(path), nil
}

// SubmitQuizAttempt is the resolver for the submitQuizAttempt field.
func (r *mutationResolver) SubmitQuizAttempt(ctx context.Context, input generated.SubmitQuizAttemptInput) (*generated.QuizAttempt, error) {
	attempt, ok, err := r.svc.SubmitQuizAttempt(ctx, input.QuizID, input.LearnerID, input.Answers)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToAttempt(attempt), nil
}

// CreateDxInitiative is the resolver for the createDxInitiative field.
func (r *mutationResolver) CreateDxInitiative(ctx context.Context, input generated.CreateDxInitiativeInput) (*generated.DxInitiative, error) {
	item, err := r.svc.CreateDxInitiative(ctx, gqlconv.DxInitiativeFromInput(input))
	if err != nil {
		return nil, err
	}
	return gqlconv.ToDxInitiative(item), nil
}

// CreateCrmContact is the resolver for the createCrmContact field.
func (r *mutationResolver) CreateCrmContact(ctx context.Context, input generated.CreateCrmContactInput) (*generated.CrmContact, error) {
	item, err := r.svc.CreateCrmContact(ctx, gqlconv.CrmContactFromInput(input))
	if err != nil {
		return nil, err
	}
	return gqlconv.ToCrmContact(item), nil
}

// CreateCrmInteraction is the resolver for the createCrmInteraction field.
func (r *mutationResolver) CreateCrmInteraction(ctx context.Context, contactID string, kind string, summary string) (*generated.CrmInteraction, error) {
	item, err := r.svc.CreateCrmInteraction(ctx, contactID, kind, summary)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToCrmInteraction(item), nil
}

// ClockIn is the resolver for the clockIn field.
func (r *mutationResolver) ClockIn(ctx context.Context, note *string) (*generated.AttendanceRecord, error) {
	n := ""
	if note != nil {
		n = *note
	}
	item, err := r.svc.ClockIn(ctx, n)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToAttendanceRecord(item), nil
}

// ClockOut is the resolver for the clockOut field.
func (r *mutationResolver) ClockOut(ctx context.Context) (*generated.AttendanceRecord, error) {
	item, err := r.svc.ClockOut(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToAttendanceRecord(item), nil
}

// CreateLeaveRequest is the resolver for the createLeaveRequest field.
func (r *mutationResolver) CreateLeaveRequest(ctx context.Context, input generated.CreateLeaveRequestInput) (*generated.LeaveRequest, error) {
	start, err := time.Parse("2006-01-02", input.StartDate)
	if err != nil {
		return nil, err
	}
	end, err := time.Parse("2006-01-02", input.EndDate)
	if err != nil {
		return nil, err
	}
	reason := ""
	if input.Reason != nil {
		reason = *input.Reason
	}
	item, err := r.svc.CreateLeaveRequest(ctx, start, end, reason)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToLeaveRequest(item), nil
}

// ApproveLeaveRequest is the resolver for the approveLeaveRequest field.
func (r *mutationResolver) ApproveLeaveRequest(ctx context.Context, id string) (*generated.LeaveRequest, error) {
	item, err := r.svc.ApproveLeaveRequest(ctx, id)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToLeaveRequest(item), nil
}

// CreateContractTemplate is the resolver for the createContractTemplate field.
func (r *mutationResolver) CreateContractTemplate(ctx context.Context, name string, body string) (*generated.ContractTemplate, error) {
	item, err := r.svc.CreateContractTemplate(ctx, name, body)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToContractTemplate(item), nil
}

// CreateContract is the resolver for the createContract field.
func (r *mutationResolver) CreateContract(ctx context.Context, input generated.CreateContractInput) (*generated.Contract, error) {
	templateID := ""
	if input.TemplateID != nil {
		templateID = *input.TemplateID
	}
	body := ""
	if input.Body != nil {
		body = *input.Body
	}
	partyEmail := ""
	if input.PartyEmail != nil {
		partyEmail = *input.PartyEmail
	}
	item, err := r.svc.CreateContract(ctx, templateID, input.Title, input.PartyName, partyEmail, body)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToContract(item), nil
}

// SignContract is the resolver for the signContract field.
func (r *mutationResolver) SignContract(ctx context.Context, id string) (*generated.Contract, error) {
	item, err := r.svc.SignContract(ctx, id)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToContract(item), nil
}

// SendConsultMessage is the resolver for the sendConsultMessage field.
func (r *mutationResolver) SendConsultMessage(ctx context.Context, threadID *string, message string) (*generated.ConsultMessageReply, error) {
	tid := ""
	if threadID != nil {
		tid = *threadID
	}
	reply, err := r.svc.SendConsultationModule(ctx, tid, message)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToConsultMessageReply(reply), nil
}

// CreateRagDocument is the resolver for the createRagDocument field.
func (r *mutationResolver) CreateRagDocument(ctx context.Context, input generated.CreateRagDocumentInput) (*generated.RagDocument, error) {
	item, err := r.svc.CreateRagDocument(ctx, gqlconv.RagDocumentFromInput(input))
	if err != nil {
		return nil, err
	}
	return gqlconv.ToRagDocument(item), nil
}

// SetSaasModuleEnabled is the resolver for the setSaasModuleEnabled field.
func (r *mutationResolver) SetSaasModuleEnabled(ctx context.Context, code generated.SaasModuleCode, enabled bool) (*generated.SaasModule, error) {
	item, err := r.svc.SetSaasModuleEnabled(ctx, models.SaasModuleCode(code), enabled)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToSaasModule(item), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*generated.Health, error) {
	return gqlconv.ToHealth(), nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*generated.DashboardStats, error) {
	d, err := r.svc.Dashboard(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToDashboard(d), nil
}

// CurrentSession is the resolver for the currentSession field.
func (r *queryResolver) CurrentSession(ctx context.Context) (*generated.Session, error) {
	sess, err := r.svc.CurrentSession(ctx)
	if err != nil || sess == nil {
		return nil, err
	}
	mods, err := r.svc.ListSaasModules(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToSessionWithModules(*sess, mods), nil
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context) (*generated.Organization, error) {
	o, err := r.svc.GetOrganization(ctx)
	if err != nil {
		return nil, err
	}
	mods, err := r.svc.ListSaasModules(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToOrganizationWithModules(o, mods), nil
}

// UsageSummary is the resolver for the usageSummary field.
func (r *queryResolver) UsageSummary(ctx context.Context) (*generated.UsageSummary, error) {
	u, err := r.svc.UsageSummary(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToUsageSummary(u), nil
}

// TeamMembers is the resolver for the teamMembers field.
func (r *queryResolver) TeamMembers(ctx context.Context) ([]*generated.TeamMember, error) {
	members, users, err := r.svc.ListTeamMembers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.TeamMember, len(members))
	for i, m := range members {
		out[i] = gqlconv.ToTeamMember(m, users[i])
	}
	return out, nil
}

// AnalyticsBoard is the resolver for the analyticsBoard field.
func (r *queryResolver) AnalyticsBoard(ctx context.Context, periodDays *int) (*generated.AnalyticsBoard, error) {
	days := 30
	if periodDays != nil {
		days = *periodDays
	}
	b, err := r.svc.AnalyticsBoard(ctx, days)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToAnalyticsBoard(b), nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context, category *models.VideoCategory, skillLevel *models.SkillLevel, search *string, page *int, pageSize *int) (*generated.VideoPage, error) {
	p, ps := pageArgs(page, pageSize)
	s := ""
	if search != nil {
		s = *search
	}
	result, err := r.svc.PaginateVideos(ctx, gqlconv.EnumStr(category), gqlconv.LevelStr(skillLevel), s, p, ps)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToVideoPage(result), nil
}

// Video is the resolver for the video field.
func (r *queryResolver) Video(ctx context.Context, id string) (*generated.Video, error) {
	v, ok, err := r.svc.GetVideo(ctx, id)
	if err != nil || !ok {
		return nil, err
	}
	return gqlconv.ToVideo(v), nil
}

// FeaturedVideos is the resolver for the featuredVideos field.
func (r *queryResolver) FeaturedVideos(ctx context.Context) ([]*generated.Video, error) {
	videos, err := r.svc.FeaturedVideos(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToVideos(videos), nil
}

// Instructors is the resolver for the instructors field.
func (r *queryResolver) Instructors(ctx context.Context) ([]*generated.Instructor, error) {
	list, err := r.svc.ListInstructors(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Instructor, len(list))
	for i, inst := range list {
		out[i] = gqlconv.ToInstructor(inst)
	}
	return out, nil
}

// Instructor is the resolver for the instructor field.
func (r *queryResolver) Instructor(ctx context.Context, id string) (*generated.Instructor, error) {
	if l := loadersFrom(ctx); l != nil {
		thunk := l.InstructorByID.Load(ctx, id)
		return thunk()
	}
	i, ok, err := r.svc.GetInstructor(ctx, id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToInstructor(i), nil
}

// LearningPaths is the resolver for the learningPaths field.
func (r *queryResolver) LearningPaths(ctx context.Context, category *models.VideoCategory, skillLevel *models.SkillLevel) ([]*generated.LearningPath, error) {
	list, err := r.svc.ListPaths(ctx, gqlconv.EnumStr(category), gqlconv.LevelStr(skillLevel))
	if err != nil {
		return nil, err
	}
	return gqlconv.ToPaths(list), nil
}

// LearningPath is the resolver for the learningPath field.
func (r *queryResolver) LearningPath(ctx context.Context, id string) (*generated.LearningPath, error) {
	path, ok, err := r.svc.GetPath(ctx, id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToPath(path), nil
}

// MyProgress is the resolver for the myProgress field.
func (r *queryResolver) MyProgress(ctx context.Context, learnerID string) ([]*generated.WatchProgress, error) {
	list, err := r.svc.ListProgress(ctx, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.WatchProgress, len(list))
	for i, p := range list {
		out[i] = gqlconv.ToProgress(p)
	}
	return out, nil
}

// MyBookmarks is the resolver for the myBookmarks field.
func (r *queryResolver) MyBookmarks(ctx context.Context, learnerID string) ([]*generated.Bookmark, error) {
	list, err := r.svc.ListBookmarks(ctx, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Bookmark, len(list))
	for i, b := range list {
		out[i] = gqlconv.ToBookmark(b)
	}
	return out, nil
}

// VideoNotes is the resolver for the videoNotes field.
func (r *queryResolver) VideoNotes(ctx context.Context, videoID string, learnerID string) ([]*generated.VideoNote, error) {
	list, err := r.svc.ListNotes(ctx, videoID, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.VideoNote, len(list))
	for i, n := range list {
		out[i] = gqlconv.ToNote(n)
	}
	return out, nil
}

// Quizzes is the resolver for the quizzes field.
func (r *queryResolver) Quizzes(ctx context.Context, videoID *string) ([]*generated.Quiz, error) {
	vid := ""
	if videoID != nil {
		vid = *videoID
	}
	list, err := r.svc.ListQuizzes(ctx, vid)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Quiz, len(list))
	for i, q := range list {
		out[i] = gqlconv.ToQuiz(q)
	}
	return out, nil
}

// Quiz is the resolver for the quiz field.
func (r *queryResolver) Quiz(ctx context.Context, id string) (*generated.Quiz, error) {
	q, ok, err := r.svc.GetQuiz(ctx, id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	return gqlconv.ToQuiz(q), nil
}

// MyQuizAttempts is the resolver for the myQuizAttempts field.
func (r *queryResolver) MyQuizAttempts(ctx context.Context, learnerID string) ([]*generated.QuizAttempt, error) {
	list, err := r.svc.ListAttempts(ctx, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.QuizAttempt, len(list))
	for i, a := range list {
		out[i] = gqlconv.ToAttempt(a)
	}
	return out, nil
}

// MyCertificates is the resolver for the myCertificates field.
func (r *queryResolver) MyCertificates(ctx context.Context, learnerID string) ([]*generated.Certificate, error) {
	list, err := r.svc.ListCertificates(ctx, learnerID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Certificate, len(list))
	for i, c := range list {
		out[i] = gqlconv.ToCertificate(c)
	}
	return out, nil
}

// SaasModules is the resolver for the saasModules field.
func (r *queryResolver) SaasModules(ctx context.Context) ([]*generated.SaasModule, error) {
	list, err := r.svc.ListSaasModules(ctx)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToSaasModules(list), nil
}

// DxInitiatives is the resolver for the dxInitiatives field.
func (r *queryResolver) DxInitiatives(ctx context.Context) ([]*generated.DxInitiative, error) {
	list, err := r.svc.ListDxInitiatives(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.DxInitiative, len(list))
	for i, item := range list {
		out[i] = gqlconv.ToDxInitiative(item)
	}
	return out, nil
}

// CrmContacts is the resolver for the crmContacts field.
func (r *queryResolver) CrmContacts(ctx context.Context) ([]*generated.CrmContact, error) {
	list, err := r.svc.ListCrmContacts(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.CrmContact, len(list))
	for i, item := range list {
		out[i] = gqlconv.ToCrmContact(item)
	}
	return out, nil
}

// CrmInteractions is the resolver for the crmInteractions field.
func (r *queryResolver) CrmInteractions(ctx context.Context, contactID string) ([]*generated.CrmInteraction, error) {
	list, err := r.svc.ListCrmInteractions(ctx, contactID)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.CrmInteraction, len(list))
	for i, item := range list {
		out[i] = gqlconv.ToCrmInteraction(item)
	}
	return out, nil
}

// AttendanceRecords is the resolver for the attendanceRecords field.
func (r *queryResolver) AttendanceRecords(ctx context.Context) ([]*generated.AttendanceRecord, error) {
	list, err := r.svc.ListAttendanceRecords(ctx, "")
	if err != nil {
		return nil, err
	}
	out := make([]*generated.AttendanceRecord, len(list))
	for i, item := range list {
		out[i] = gqlconv.ToAttendanceRecord(item)
	}
	return out, nil
}

// LeaveRequests is the resolver for the leaveRequests field.
func (r *queryResolver) LeaveRequests(ctx context.Context) ([]*generated.LeaveRequest, error) {
	list, err := r.svc.ListLeaveRequests(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.LeaveRequest, len(list))
	for i, item := range list {
		out[i] = gqlconv.ToLeaveRequest(item)
	}
	return out, nil
}

// ContractTemplates is the resolver for the contractTemplates field.
func (r *queryResolver) ContractTemplates(ctx context.Context) ([]*generated.ContractTemplate, error) {
	list, err := r.svc.ListContractTemplates(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.ContractTemplate, len(list))
	for i, item := range list {
		out[i] = gqlconv.ToContractTemplate(item)
	}
	return out, nil
}

// Contracts is the resolver for the contracts field.
func (r *queryResolver) Contracts(ctx context.Context) ([]*generated.Contract, error) {
	list, err := r.svc.ListContracts(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.Contract, len(list))
	for i, item := range list {
		out[i] = gqlconv.ToContract(item)
	}
	return out, nil
}

// ConsultThreads is the resolver for the consultThreads field.
func (r *queryResolver) ConsultThreads(ctx context.Context) ([]*generated.ConsultThread, error) {
	list, err := r.svc.ListConsultThreadsModule(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.ConsultThread, len(list))
	for i, t := range list {
		out[i] = gqlconv.ToConsultThread(t, nil)
	}
	return out, nil
}

// ConsultThread is the resolver for the consultThread field.
func (r *queryResolver) ConsultThread(ctx context.Context, id string) (*generated.ConsultThread, error) {
	t, msgs, err := r.svc.GetConsultThreadModule(ctx, id)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToConsultThread(t, msgs), nil
}

// RagDocuments is the resolver for the ragDocuments field.
func (r *queryResolver) RagDocuments(ctx context.Context) ([]*generated.RagDocument, error) {
	list, err := r.svc.ListRagDocuments(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.RagDocument, len(list))
	for i, item := range list {
		out[i] = gqlconv.ToRagDocument(item)
	}
	return out, nil
}

// RagSearch is the resolver for the ragSearch field.
func (r *queryResolver) RagSearch(ctx context.Context, query string, limit *int) ([]*generated.RagSearchHit, error) {
	n := 5
	if limit != nil {
		n = *limit
	}
	hits, err := r.svc.SearchRagDocuments(ctx, query, n)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToRagSearchHits(hits), nil
}

// RagAnswer is the resolver for the ragAnswer field.
func (r *queryResolver) RagAnswer(ctx context.Context, query string) (*generated.RagAnswer, error) {
	answer, hits, err := r.svc.RagAnswer(ctx, query)
	if err != nil {
		return nil, err
	}
	return gqlconv.ToRagAnswer(answer, hits), nil
}

// DashboardUpdated is the resolver for the dashboardUpdated field.
func (r *subscriptionResolver) DashboardUpdated(ctx context.Context) (<-chan *generated.DashboardStats, error) {
	oid, err := r.svc.OrgID(ctx)
	if err != nil {
		return nil, err
	}
	ch := r.svc.Realtime.SubscribeDashboard(oid)
	go func() {
		<-ctx.Done()
		r.svc.Realtime.UnsubscribeDashboard(oid, ch)
	}()
	return ch, nil
}

// ProgressUpdated is the resolver for the progressUpdated field.
func (r *subscriptionResolver) ProgressUpdated(ctx context.Context, learnerID string) (<-chan *generated.WatchProgress, error) {
	ch := r.svc.Realtime.SubscribeProgress(learnerID)
	go func() {
		<-ctx.Done()
		r.svc.Realtime.UnsubscribeProgress(learnerID, ch)
	}()
	return ch, nil
}

// LearningActivity is the resolver for the learningActivity field.
func (r *subscriptionResolver) LearningActivity(ctx context.Context, learnerID string) (<-chan *generated.LearningActivityEvent, error) {
	ch := r.svc.Realtime.SubscribeActivity(learnerID)
	go func() {
		<-ctx.Done()
		r.svc.Realtime.UnsubscribeActivity(learnerID, ch)
	}()
	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
